[build]
  publish = "public"
  command = "echo 'No build step required'"
  functions = "netlify/functions"

[dev]
  port = 8888

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VALUESERP_API"

[[redirects]]
  from = "/seo"
  to = "/seo.html"
  status = 200
